
"""Database enums used across models."""

import enum


class CompanyStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    INACTIVE = "INACTIVE"


class UserRole(str, enum.Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    COMPANY_ADMIN = "COMPANY_ADMIN"
    CLIENT = "CLIENT"


class ClientStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    DEFAULTER = "DEFAULTER"
    IN_NEGOTIATION = "IN_NEGOTIATION"
    RESCINDED = "RESCINDED"


class LotStatus(str, enum.Enum):
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    SOLD = "SOLD"


class ClientLotStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    RESCINDED = "RESCINDED"


class InvoiceStatus(str, enum.Enum):
    PENDING = "PENDING"
    PAID = "PAID"
    OVERDUE = "OVERDUE"
    CANCELLED = "CANCELLED"


class ServiceOrderStatus(str, enum.Enum):
    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class ReferralStatus(str, enum.Enum):
    PENDING = "PENDING"
    CONTACTED = "CONTACTED"
    CONVERTED = "CONVERTED"
    LOST = "LOST"


class BoletoStatus(str, enum.Enum):
    NORMAL = "NORMAL"
    LIQUIDADO = "LIQUIDADO"
    VENCIDO = "VENCIDO"
    CANCELADO = "CANCELADO"
    PENDING_APPROVAL = "PENDING_APPROVAL"


class ContractEventType(str, enum.Enum):
    PAYMENT = "PAYMENT"
    OVERDUE = "OVERDUE"
    RENEGOTIATION = "RENEGOTIATION"
    ADJUSTMENT = "ADJUSTMENT"
    MANUAL_WRITEOFF = "MANUAL_WRITEOFF"
    DISCOUNT_APPLIED = "DISCOUNT_APPLIED"
    PENALTY_REMOVED = "PENALTY_REMOVED"
    BOLETO_ISSUED = "BOLETO_ISSUED"
    BOLETO_CANCELLED = "BOLETO_CANCELLED"
    SECOND_COPY = "SECOND_COPY"
    RESCISSION_STARTED = "RESCISSION_STARTED"
    RESCISSION_COMPLETED = "RESCISSION_COMPLETED"
    STATUS_CHANGE = "STATUS_CHANGE"
    NOTE = "NOTE"


class RenegotiationStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    APPLIED = "APPLIED"
    CANCELLED = "CANCELLED"


class RescissionStatus(str, enum.Enum):
    REQUESTED = "REQUESTED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
