
"""Database enums used across models."""

import enum


class CompanyStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    INACTIVE = "INACTIVE"


class UserRole(str, enum.Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    COMPANY_ADMIN = "COMPANY_ADMIN"
    CLIENT = "CLIENT"


class ClientStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    DEFAULTER = "DEFAULTER"
    IN_NEGOTIATION = "IN_NEGOTIATION"
    RESCINDED = "RESCINDED"


class LotStatus(str, enum.Enum):
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    SOLD = "SOLD"


class ClientLotStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    RESCINDED = "RESCINDED"


class InvoiceStatus(str, enum.Enum):
    PENDING = "PENDING"
    PAID = "PAID"
    OVERDUE = "OVERDUE"
    CANCELLED = "CANCELLED"


class ServiceOrderStatus(str, enum.Enum):
    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class ReferralStatus(str, enum.Enum):
    PENDING = "PENDING"
    CONTACTED = "CONTACTED"
    CONVERTED = "CONVERTED"
    LOST = "LOST"


class BoletoTag(str, enum.Enum):
    ENTRADA_PARCELADA = "ENTRADA_PARCELADA"
    PARCELA_CONTRATO = "PARCELA_CONTRATO"
    SERVICO_AVULSO = "SERVICO_AVULSO"
    SEGUNDA_VIA = "SEGUNDA_VIA"
    RENEGOCIACAO = "RENEGOCIACAO"


class BoletoStatus(str, enum.Enum):
    NORMAL = "NORMAL"
    LIQUIDADO = "LIQUIDADO"
    VENCIDO = "VENCIDO"
    CANCELADO = "CANCELADO"
    NEGATIVADO = "NEGATIVADO"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    BAIXA_MANUAL = "BAIXA_MANUAL"


class WriteoffType(str, enum.Enum):
    AUTOMATICA_BANCO = "AUTOMATICA_BANCO"
    MANUAL_ADMIN = "MANUAL_ADMIN"


class AdjustmentIndex(str, enum.Enum):
    IPCA = "IPCA"
    IGPM = "IGPM"
    CUB = "CUB"
    INPC = "INPC"


class AdjustmentFrequency(str, enum.Enum):
    MONTHLY = "MONTHLY"
    QUARTERLY = "QUARTERLY"
    SEMIANNUAL = "SEMIANNUAL"
    ANNUAL = "ANNUAL"


class ContractEventType(str, enum.Enum):
    PAYMENT = "PAYMENT"
    OVERDUE = "OVERDUE"
    RENEGOTIATION = "RENEGOTIATION"
    ADJUSTMENT = "ADJUSTMENT"
    MANUAL_WRITEOFF = "MANUAL_WRITEOFF"
    DISCOUNT_APPLIED = "DISCOUNT_APPLIED"
    PENALTY_REMOVED = "PENALTY_REMOVED"
    BOLETO_ISSUED = "BOLETO_ISSUED"
    BOLETO_CANCELLED = "BOLETO_CANCELLED"
    SECOND_COPY = "SECOND_COPY"
    RESCISSION_STARTED = "RESCISSION_STARTED"
    RESCISSION_COMPLETED = "RESCISSION_COMPLETED"
    STATUS_CHANGE = "STATUS_CHANGE"
    NOTE = "NOTE"
    TRANSFER = "TRANSFER"
    AUTO_RESCISSION = "AUTO_RESCISSION"
    CYCLE_APPROVED = "CYCLE_APPROVED"
    EARLY_PAYOFF_REQUEST = "EARLY_PAYOFF_REQUEST"


class CycleApprovalStatus(str, enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class TransferStatus(str, enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class EarlyPayoffStatus(str, enum.Enum):
    PENDING = "PENDING"
    CONTACTED = "CONTACTED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class RenegotiationStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    APPLIED = "APPLIED"
    CANCELLED = "CANCELLED"


class RescissionStatus(str, enum.Enum):
    REQUESTED = "REQUESTED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class DocumentType(str, enum.Enum):
    RG = "RG"
    CPF = "CPF"
    COMPROVANTE_RESIDENCIA = "COMPROVANTE_RESIDENCIA"
    CNH = "CNH"
    CONTRATO = "CONTRATO"
    OUTROS = "OUTROS"


class DocumentStatus(str, enum.Enum):
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class ServiceRequestStatus(str, enum.Enum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    WAITING_CLIENT = "WAITING_CLIENT"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class ServiceRequestPriority(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    URGENT = "URGENT"


class ServiceRequestType(str, enum.Enum):
    MANUTENCAO = "MANUTENCAO"
    SUPORTE = "SUPORTE"
    FINANCEIRO = "FINANCEIRO"
    DOCUMENTACAO = "DOCUMENTACAO"
    OUTROS = "OUTROS"


class NotificationType(str, enum.Enum):
    BOLETO_EMITIDO = "BOLETO_EMITIDO"
    BOLETO_VENCIDO = "BOLETO_VENCIDO"
    PAGAMENTO_CONFIRMADO = "PAGAMENTO_CONFIRMADO"
    DOCUMENTO_APROVADO = "DOCUMENTO_APROVADO"
    DOCUMENTO_REJEITADO = "DOCUMENTO_REJEITADO"
    SOLICITACAO_ATUALIZADA = "SOLICITACAO_ATUALIZADA"
    GERAL = "GERAL"
    CICLO_PENDENTE = "CICLO_PENDENTE"
    TRANSFERENCIA_CONTRATO = "TRANSFERENCIA_CONTRATO"
    ANTECIPACAO_SOLICITADA = "ANTECIPACAO_SOLICITADA"
    DISTRATO_AUTOMATICO = "DISTRATO_AUTOMATICO"


class WhatsAppProviderType(str, enum.Enum):
    UAZAPI = "UAZAPI"
    META = "META"


class IndexSource(str, enum.Enum):
    MANUAL = "MANUAL"
    BCB_API = "BCB_API"
